options:
  volume-backend-name:
    type: string
    default: powermax
    description: Volume backend name for the backend. 
  protocol:
    type: string
    default: FC
    description: |
      Storage protocol to use with the array. Can be either FC or iSCSI.
  san-ip:
    type: string
    default: !!null ""
    description: UniSphere IP used to access the array.
  san-login:
    type: string
    default: admin
    description: Username used to log on UniSphere.
  san-password:
    type: string
    default: password
    description: Password used to authenticate in UniSphere.
  powermax-array:
    type: string
    description: Serial number of the array to connect to.
  powermax-port-groups:
    type: string
    description: |
      List of port groups containing frontend ports configured prior for
      server connection.
  powermax-service-level:
    type: string
    description: |
      Service level to use for provisioning storage. Setting this as 
      an extra spec in pool_name is preferable.
  powermax-srp:
    type: string
    description: Storage resource pool on array to use for provisioning
  retries:
    type: string
    description: Use this value to specify number of retries.
  u4p-failover-autofailback:
    type: boolean
    description: |
      If the driver should automatically failback to the primary instance
      of Unisphere when a successful connection is re-established.
  use-multipath-for-image-xfer:
    type: boolean
    description: Use multipath for image xfer.
