name: Build and test

on: workflow_dispatch

jobs:
  tests:
    uses: ./.github/workflows/tests.yml
        
  build:
    name: Build the charm
    needs: [tests]
    runs-on: Ubuntu-22.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Setup LXD
        uses: canonical/setup-lxd@v0.1.2
        with:
          channel: latest/stable
      - name: Build charm
        id: builder
        run: |
          sudo snap install charmcraft --classic
          charmcraft pack -v
