name: Charm Analysis

on:
  workflow_dispatch:

jobs:
  build:
    name: Build the charm
    uses: canonical/data-platform-workflows/.github/workflows/build_charm.yaml@v0.0.0
    permissions:
      actions: write
    
  integration:
    name: Runs integration tests
    needs: [build]
    runs-on: charm-runner-1
    
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Download packed charm
      uses: actions/dowload-artifact@v3
      with: ${{ needs.build.outputs.artifact-name }}

    - name: Install concierge
      run: sudo snap install --classic concierge

    - name: Install juju and bootstrap
      run: |
        sudo concierge -v prepare \
            --juju-channel=2.9/stable \
            --charmcraft-channel=3.x/stable \
            --preset machine
    
    - name: Install dependencies
      run: python -m pip install tox

    - name: Run integration tests
      run: tox -vve func
      env: 
        PACKED_CHARM: ${{ needs.build.outputs.charms }}
      
