name: Charm Analysis

on:
  workflow_dispatch:

jobs:
  pack:
    name: Build and pack the charm
    runs-on: charm-runner-1
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Setup LXD
        uses: canonical/setup-lxd@v0.1.2
        with:
          channel: latest/stable
      - name: Build charm
        id: builder
        run: |
          sudo snap install charmcraft --classic
          charmcraft pack -v
    
  integration:
    name: Runs functional tests
    runs-on: charm-runner-1
    
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Install concierge
      run: sudo snap install --classic concierge

    - name: Install juju and bootstrap
      run: |
        sudo concierge -v prepare \
            --juju-channel=2.9/stable \
            --charmcraft-channel=3.x/stable \
            --preset machine
    
    - name: Install dependencies
      run: python -m pip install tox

    - name: Run integration tests
      run: tox -vve func
      
