name: Debug with Tailscale
on: workflow_dispatch

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Connect to Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci

      - name: Get Tailscale IP
        id: tailscale-ip
        run: |
          TAILSCALE_IP=$(tailscale ip -4)
          echo "ip=$TAILSCALE_IP" >> $GITHUB_OUTPUT
          echo "🌐 Runner accessible at: $TAILSCALE_IP"

      - name: Setup SSH Debug (Tailscale Direct)
        uses: lexbritvin/ssh-session-action@v1
        with:
          # No jump host needed - direct connection via Tailscale
          ssh-server-host: ${{ steps.tailscale-ip.outputs.ip }}
          ssh-server-port: 2223
          use-actor-ssh-keys: true
          wait-timeout: 3600
